### ISSUE TITLE
Pressing enter on new deck name screen clears the name 

### ISSUE THREAD

**Issue by calmackenzie** [calmackenzie/VG1819#377]
Pressing enter on new deck name screen clears the name instead of bringing the player to the next screen.
Steps to reproduce:
1. Launch game
2. Click "Decks"
3. Click "Add New Deck"
4. Type something
5. Press Enter

**Comment by VibrantJack** [comment]
Unless you guys changed the logic behind the String input textboxes, I doubt we can fix this

**Comment by calmackenzie** [comment]
This is pretty fixable. Just use the callback from inputmanager when the player presses enter when in pollmode
