### ISSUE TITLE
Crash from hovering units in hand

### ISSUE THREAD

**Issue by calmackenzie** [calmackenzie/VG1819#431]
I believe this is a demon/ancients crash:
Specific deck used:
Eldritch Lord as commander
2x  each unit starting with "Eternal Eye"

Reproduction steps:
1. Enter testing grounds with above deck
2. Hover over cards in hand
3. If no crash, end turn
4. Repeat 2-3
5. Crash

Callstack:
![image](https://user-images.githubusercontent.com/31747378/55571335-b79f2e80-56db-11e9-8905-b81ec82ed69b.png)

CardContext's text was "Gorefiend"
![image](https://user-images.githubusercontent.com/31747378/55571395-d1d90c80-56db-11e9-9d9e-d514f21137ce.png)

m_unitData was null ? 
![image](https://user-images.githubusercontent.com/31747378/55571494-ff25ba80-56db-11e9-919d-2073d13cbaa7.png)

Crash was from trying to `getComponent` on null gameObject from `m_unitData`

**Comment by calmackenzie** [comment]
The crashing player had two gorefiends in hand at time

**Comment by calmackenzie** [comment]
Might be triggered from hovering over one of them?

**Comment by calmackenzie** [comment]
Ok, (sorry for flooding comments) the crash is from hovering cards in the hand, updating issue as result

**Comment by kamarapala** [comment]
I'm taking a look at it since it concerns CardContext/StatusIcons

**Comment by kamarapala** [comment]
Issue was that a flag to indicate to update by GO or by ID in CardContext was being set after the unit was set.
This should have caused problems for all units, but it seemed to only cause problems for Gorefiend and I couldn't figure out why only that card.

Regardless, I have a fix that sets those flags before setting the units.
