### ISSUE TITLE
Shader Warnings

### ISSUE THREAD

**Issue by kamarapala** [calmackenzie/VG1819#435]
The following warnings get output to console when the project starts up
```
0(32) : warning C7050: "light1Out" might be used before being initialized
0(33) : warning C7050: "light2Out" might be used before being initialized
```
I took a look through the shaders that had those variables and it didn't seem like anything could happen, but I may have missed it.
 
Should this be of concern @calmackenzie ?

**Comment by calmackenzie** [comment]
oops; I will fix this as undefined stuff will happen with pixel colour when they are outside of light's range
