### ISSUE TITLE
Gem pickup in capture mode is too high up

### ISSUE THREAD

**Issue by calmackenzie** [calmackenzie/VG1819#461]
![image](https://user-images.githubusercontent.com/31747378/55688323-95ace280-594d-11e9-823d-3c978f856a30.png)

**Comment by austinbrianrogers** [comment]
![image](https://user-images.githubusercontent.com/17730830/55688362-123fc100-594e-11e9-8802-a5cc5dcc282c.png)

Gems appear to be spawned in different spots too (this is a pic of my client)
