### ISSUE TITLE
Servant Sacrifice did not reduce cost of a unit.

### ISSUE THREAD

**Issue by austinbrianrogers** [calmackenzie/VG1819#463]
Forgot to grab a picture. I will post one if it happens again during testing.

**Comment by calmackenzie** [comment]
My bad, tagged the wrong issue in the PR D:

**Comment by SRJYC** [comment]
Sacrifice will reduce cost, but the card on hand will not update, at least this what in test ground.

I have 1 resource.
Normal card. Can't summon.
![image](https://user-images.githubusercontent.com/39406264/55822686-82794e80-5ad6-11e9-8c6c-29b6648d63a4.png)

But another card can. Its cost is reduced.
![image](https://user-images.githubusercontent.com/39406264/55822722-9c1a9600-5ad6-11e9-9bf3-907969b92dc1.png)


But I found another bug, that it will make next unit can't take action. I am fixing it.

**Comment by SRJYC** [comment]
When you hover on the card, the card context is updated by Id, so it will not show any changes in hand.
I have no idea to fix it.
@austinbrianrogers

**Comment by kamarapala** [comment]
I'm taking a look at it.

I'm pretty sure that early on, the cards had unit components that weren't attached to GOs, so I had to update them by ID. Now they are attached to the card GO, so we should be able to update cards in hand by GO as well, which would update the cost as well

**Comment by kamarapala** [comment]
![image](https://user-images.githubusercontent.com/31244529/55917920-9b156180-5bc7-11e9-8aaf-205f6fc8be28.png)

Seems to work. I'll put up a PR shortly
