### ISSUE TITLE
Ancient unit could not move onto swamp tile from standing on unowned mud

### ISSUE THREAD

**Issue by calmackenzie** [calmackenzie/VG1819#465]
![image](https://user-images.githubusercontent.com/31747378/55688929-d8be8400-5954-11e9-8a96-26ee91ace61c.png)

**Comment by calmackenzie** [comment]
related?
Commander can move two mud tiles but not 1 mud then 1 swamp
![image](https://user-images.githubusercontent.com/31747378/55689184-e75a6a80-5957-11e9-9a34-884e57283d28.png)

**Comment by SRJYC** [comment]
Swamp cost 2 to move。1 mud then 1 swamp needs 3 movement power.
Mud will -1 mv for unit who stand on it. 
So some units will have 1 mv and commander will have 2 mv at turn start. 
So it can't move to swamp.

May be change swamp mv cost to 1.5?

**Comment by SRJYC** [comment]
No, change mv cost won't really solve the problem.
I will change the map and leave a road. Mud will not completely surround center.
