### ISSUE TITLE
[Crash] Game crash from Vampiric Protection (Monument Status Ability)

### ISSUE THREAD

**Issue by calmackenzie** [calmackenzie/VG1819#467]
Chain of events:
1. Used Lord's Order on Evil Fiend
2. Used Monument's ability on Evil Fiend
3. crash

Screenshot of frame of  crash:
![image](https://user-images.githubusercontent.com/31747378/55689062-a9107b80-5956-11e9-849d-79726be14d3e.png)

![image](https://user-images.githubusercontent.com/31747378/55689067-bcbbe200-5956-11e9-8085-b008ebb0c85e.png)
![image](https://user-images.githubusercontent.com/31747378/55689081-e8d76300-5956-11e9-8f88-c8439c48310b.png)
![image](https://user-images.githubusercontent.com/31747378/55689086-f260cb00-5956-11e9-82ef-31ef5aef0ed4.png)

**Comment by calmackenzie** [comment]
Issue also occurred on turn end of another ancient's unit that did not have Lord's Order on it

**Comment by SRJYC** [comment]
I think I got the problem.
Vampiric_Curse will steal hp from attached unit and restore same amount hp to caster.
But caster can be died, which leaves m_caster to be random pointer.

Lords order is same, but its owner is commander. If commander dies, game ends, so it won't trigger exception.
