### ISSUE TITLE
Settings Menu Textboxes are Occasionally Enabled During Game Startup

### ISSUE THREAD

**Issue by kamarapala** [calmackenzie/VG1819#473]
- Happens rarely, but the percentage textboxes for sfx/bgm/ambient can be enabled when mainscene.json is loaded, even though the rest of the options menu is disabled and hidden
- When this happens, opening the settings/pause menu and closing it will fix it

- No screenshot since I closed the game and could not get the bug to happen again at time of creating ticket, but will update with one when it happens

**Comment by ohheythere2** [comment]
I believe pull request #458 fixes this

**Comment by calmackenzie** [comment]
I'm going to close this -- if it happens again this issue should be reopened
